blank_issues_enabled: true
contact_links:
  - name: 📋 Issue Guidelines
    url: https://github.com/PHSKC-APDE/rads/blob/main/.github/ISSUE_TEMPLATE/ISSUE_GUIDELINES.md
    about: Read our full guidelines with examples of good and bad issue submissions