<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">
<title>age_standardize()</title>
<style type="text/css">
/**
 * Prism.s theme ported from highlight.js's xcode style
 */
pre code {
  padding: 1em;
}
.token.comment {
  color: #007400;
}
.token.punctuation {
  color: #999;
}
.token.tag,
.token.selector {
  color: #aa0d91;
}
.token.boolean,
.token.number,
.token.constant,
.token.symbol {
  color: #1c00cf;
}
.token.property,
.token.attr-name,
.token.string,
.token.char,
.token.builtin {
  color: #c41a16;
}
.token.inserted {
  background-color: #ccffd8;
}
.token.deleted {
  background-color: #ffebe9;
}
.token.operator,
.token.entity,
.token.url,
.language-css .token.string,
.style .token.string {
  color: #9a6e3a;
}
.token.atrule,
.token.attr-value,
.token.keyword {
  color: #836c28;
}
.token.function,
.token.class-name {
  color: #DD4A68;
}
.token.regex,
.token.important,
.token.variable {
  color: #5c2699;
}
.token.important,
.token.bold {
  font-weight: bold;
}
.token.italic {
  font-style: italic;
}
</style>
<style type="text/css">
body {
  font-family: sans-serif;
  max-width: 800px;
  margin: auto;
  padding: 1em;
  line-height: 1.5;
  box-sizing: border-box;
}
body, .footnotes, code { font-size: .9em; }
li li { font-size: .95em; }
*, *:before, *:after {
  box-sizing: inherit;
}
pre, img { max-width: 100%; }
pre, pre:hover {
  white-space: pre-wrap;
  word-break: break-all;
}
pre code {
  display: block;
  overflow-x: auto;
}
code { font-family: 'DejaVu Sans Mono', 'Droid Sans Mono', 'Lucida Console', Consolas, Monaco, monospace; }
:not(pre) > code, code[class] { background-color: #F8F8F8; }
code.language-undefined, pre > code:not([class]) {
  background-color: inherit;
  border: 1px solid #eee;
}
table {
  margin: auto;
  border-top: 1px solid #666;
}
table thead th { border-bottom: 1px solid #ddd; }
th, td { padding: 5px; }
thead, tfoot, tr:nth-child(even) { background: #eee; }
blockquote {
  color: #666;
  margin: 0;
  padding-left: 1em;
  border-left: 0.5em solid #eee;
}
hr, .footnotes::before { border: 1px dashed #ddd; }
.frontmatter { text-align: center; }
#TOC .numbered li { list-style: none; }
#TOC .numbered { padding-left: 0; }
#TOC .numbered ul { padding-left: 1em; }
table, .body h2 { border-bottom: 1px solid #666; }
.body .appendix, .appendix ~ h2 { border-bottom-style: dashed; }
.footnote-ref a::before { content: "["; }
.footnote-ref a::after { content: "]"; }
.footnotes::before {
  content: "";
  display: block;
  max-width: 20em;
}

@media print {
  body {
    font-size: 12pt;
    max-width: 100%;
  }
  tr, img { page-break-inside: avoid; }
}
@media only screen and (min-width: 992px) {
  pre { white-space: pre; }
}
</style>
</head>
<body>
<div class="include-before">
</div>
<div class="frontmatter">
<div class="title"><h1>age_standardize()</h1></div>
<div class="author"><h2></h2></div>
<div class="date"><h3></h3></div>
</div>
<div class="body">
<h2 id="introduction">Introduction</h2>
<p>The comparison of crude health indicator rates across populations is often confounded by different age structures. For example, in 2019 the mean age of Hispanic King County residents was ~12.5 years younger than that of white residents (27.5 vs 40). Given this age discrepancy, we should expect higher mortality rates among white residents. However, you might be thinking, <em>“Is there a way to compare Hispanic and white mortality rates while fully accounting for their different age structures? I.e., is there a way to standardize or adjust for age?”</em></p>
<p>While you can use Poisson regression or other advanced statistical techniques to calculate age adjusted rates, for simplicity and broader comparison with the work of others, it is often beneficial to adjust your data using a standard reference population. This process is called <em><strong>age standardization</strong></em>. Age standardization answers the question, <em>“What rates would I observe if my data had the same age structure as a different population?”</em></p>
<p>There are 35 reference populations baked into <code>rads</code> (via it’s dependency on <a href="https://github.com/PHSKC-APDE/rads.data"><code>rads.data</code></a>). Their names are visible when you type <code>list_ref_pop()</code>. Here are the first five as an example:</p>
<pre><code class="language-r">list_ref_pop()[1:5]
</code></pre>
<pre><code>## [1] &quot;2000 U.S. Std Population (11 age groups)&quot;                      
## [2] &quot;2000 U.S. Std Population (18 age groups - Census P25-1130)&quot;    
## [3] &quot;2000 U.S. Std Population (19 age groups - Census P25-1130)&quot;    
## [4] &quot;2000 U.S. Std Population (single ages to 84 - Census P25-1130)&quot;
## [5] &quot;2000 U.S. Std Population (single ages to 99 - Census P25-1130)&quot;
</code></pre>
<p>The first one is the default reference population used by APDE and WA DOH. Taking a peek behind the curtain shows that each reference standard is a simple table of age ranges with their corresponding populations.</p>
<pre><code class="language-r">get_ref_pop(&quot;2000 U.S. Std Population (11 age groups)&quot;)[, 1:4]
</code></pre>
<pre><code>##          agecat age_start age_end      pop
##  1:           0         0       0  3795000
##  2:   1-4 years         1       4 15192000
##  3:  5-14 years         5      14 39977000
##  4: 15-24 years        15      24 38077000
##  5: 25-34 years        25      34 37233000
##  6: 35-44 years        35      44 44659000
##  7: 45-54 years        45      54 37030000
##  8: 55-64 years        55      64 23961000
##  9: 65-74 years        65      74 18136000
## 10: 75-84 years        75      84 12315000
## 11:   85+ years        85     120  4259000
</code></pre>
<p>The <code> age_standardize()</code> function provides a simple way to use reference populations to calculate age standardized rates. This vignette will provide some examples of how to use <code> age_standardize()</code> and how to understand its output. To get the most out of this vignette, we recommend that you type each and every bit of code into R. Doing so will almost definitely help you learn the syntax much faster than just reading the vignette or copying and pasting the code.</p>
<h2 id="age-standardize-arguments"><code>age_standardize()</code> arguments</h2>
<p>Arguments are the values that we send to a function when it is called. The standard arguments for <code>age_standardize()</code> are:</p>
<ol>
<li>
<p><code>ph.data</code> &lt;- the name of the data.table/data.frame with the data that you want to age standardize. <strong>Note:</strong> <em>ph.data must contain a numeric column named ‘age’. The sole exception is if it already has a standard population merged onto the dataset, in which case it must contain a numeric column named ‘stdpop’.</em></p>
</li>
<li>
<p><code>ref.popname</code> &lt;- a character vector whose only valid options are “none” (used when ph.data has a ‘stdpop’ column) or one of the reference standarards contained in <code>list_ref_pop()</code></p>
</li>
<li>
<p><code>collapse</code> &lt;- a logical vector (T|F), determines whether or not to to collapse the ‘age’ column in ph.data to match those in ref.popname. If your data is already collapsed / aggregated into the same age bins as your reference population, and if that variable is named “agecat”, then you can set collapse to F. The default is T</p>
</li>
<li>
<p><code>my.count</code> &lt;- a character vector, identifies the column name for the <strong>aggregated</strong> count data in ph.data. The default is “count”</p>
</li>
<li>
<p><code>my.pop</code> &lt;- a character vector, identifies the column name for the population number corresponding to the count. The default is “pop”</p>
</li>
<li>
<p><code>per</code> &lt;- an integer, used as multiplier for all rates and CI, e.g., when per = 1000, the rates are per 1000 persons. The default is 100,000</p>
</li>
<li>
<p><code>conf.level</code> &lt;- a numeric value between 0.00 &amp; 0.99, designates the confidence level (i.e., 1 - alpha) to be used in the calculations. The default is 0.95</p>
</li>
<li>
<p><code>group_by</code> &lt;- a character, specifies the variable(s) by which to stratify the rate results (if any). The default is NULL (i.e., no stratification)</p>
</li>
</ol>
<h2 id="preparing-your-datset">Preparing your datset</h2>
<p>Your dataset must have the following three columns …</p>
<ol>
<li>
<p>‘age’ or ‘agecat’: ‘age’ in single years (if collapse = T) or ‘agecat’ with the same age bins as your selected reference population (if collapse = F).</p>
</li>
<li>
<p>a count for the event (e.g., disease) for which you want to find an age standardized rate.</p>
</li>
<li>
<p>the population corresponding to the age or agecat in your original data</p>
</li>
</ol>
<hr />
<h2 id="example-1-the-basics">Example #1: The Basics</h2>
<p><strong>Create synthetic line level data for a cohort 51 to 60 years of age with a binary indicator for disease status</strong></p>
<pre><code class="language-r">library(data.table)
set.seed(98121)

temp1 &lt;- data.table(
  age = rep(51:60, 100), 
  disease = sample(0:1, 1000, replace = T), 
  pop = rep(c(seq(1000, 910, -10)), 100))

temp1[]
</code></pre>
<pre><code>##       age disease  pop
##    1:  51       0 1000
##    2:  52       1  990
##    3:  53       0  980
##    4:  54       1  970
##    5:  55       1  960
##   ---                 
##  996:  56       1  950
##  997:  57       1  940
##  998:  58       1  930
##  999:  59       1  920
## 1000:  60       0  910
</code></pre>
<p><strong>Run age_standardize with APDE’s default reference population</strong></p>
<pre><code class="language-r">age_standardize(ph.data = temp1,
                ref.popname = &quot;2000 U.S. Std Population (11 age groups)&quot;, 
                collapse = T,
                my.count = &quot;disease&quot;, 
                my.pop = &quot;pop&quot;, 
                per = 1000, 
                conf.level = 0.95)[]
</code></pre>
<pre><code>##    count    pop crude.rate crude.lci crude.uci adj.rate adj.lci adj.uci
## 1:   511 955000       0.54      0.49      0.58     0.52    0.47    0.57
##                               reference_pop
## 1: 2000 U.S. Std Population (11 age groups)
</code></pre>
<p><em>Does anything seem fishy? Think for a moment …</em></p>
<ul>
<li>
<p><strong>count</strong> is the number of events that occured (i.e., the numerator)</p>
</li>
<li>
<p><strong>pop</strong> is the population corresponding to the count (i.e., the denominator)</p>
</li>
<li>
<p><strong>crude.rate, crude.lci, &amp; crude.uci</strong> are the crude (i.e., observed) rate and CI</p>
</li>
<li>
<p><strong>adj.rate, adj.lci, &amp; adj.uci</strong> are the age standardized rate and CI</p>
</li>
</ul>
<p><em>Did you find the problem?</em></p>
<p>The problem is that the population is too big. Eyeballing the output when we created the dataset above, we see that the total population for those 51 to 60 would have to be less than 10,000 (10 age groups with max 1,000 population for each). In this case it is almost 1 million! In the description of the arguments above, it specifies that we need to <em>use aggregated count data</em>. Now you see why. Ignoring that detail caused us to inflate the population (and therefore deflate the rate and CI) 1000x.</p>
<p><strong>Aggregate (collapse) the line level data</strong></p>
<pre><code class="language-r">temp1 &lt;- temp1[, .(disease = sum(disease)), by = c(&quot;age&quot;, &quot;pop&quot;)]
temp1[]
</code></pre>
<pre><code>##     age  pop disease
##  1:  51 1000      49
##  2:  52  990      46
##  3:  53  980      50
##  4:  54  970      47
##  5:  55  960      60
##  6:  56  950      50
##  7:  57  940      61
##  8:  58  930      50
##  9:  59  920      52
## 10:  60  910      46
</code></pre>
<p><strong>Run age_standardize again &lt;&lt; this time with aggregated disease events</strong></p>
<pre><code class="language-r">ex1.1 &lt;- age_standardize(ph.data = temp1,
                      ref.popname = &quot;2000 U.S. Std Population (11 age groups)&quot;, 
                      collapse = T,
                      my.count = &quot;disease&quot;, 
                      my.pop = &quot;pop&quot;, 
                      per = 1000, 
                      conf.level = 0.95)
ex1.1[]
</code></pre>
<pre><code>##    count  pop crude.rate crude.lci crude.uci adj.rate adj.lci adj.uci
## 1:   511 9550      53.51     48.97     58.35    51.93   47.19   57.05
##                               reference_pop
## 1: 2000 U.S. Std Population (11 age groups)
</code></pre>
<p>Now that count, pop, and rates seem reasonable, let’s see what happens if we change the reference population. We’ll arbitrarily set the references population to the 36th in the list provided by <code>list_ref_pop()</code> (i.e., ‘World (WHO 2000-2025) Std Million (single ages to 99)’).</p>
<pre><code class="language-r">ex1.2 &lt;- age_standardize(ph.data = temp1,
                      ref.popname = list_ref_pop()[36], 
                      collapse = T,
                      my.count = &quot;disease&quot;, 
                      my.pop = &quot;pop&quot;, 
                      per = 1000, 
                      conf.level = 0.95)
ex1.2[]
</code></pre>
<pre><code>##    count  pop crude.rate crude.lci crude.uci adj.rate adj.lci adj.uci
## 1:   511 9550      53.51     48.97     58.35    53.34   48.81    58.2
##                                            reference_pop
## 1: World (WHO 2000-2025) Std Million (single ages to 99)
</code></pre>
<p>As we’d expect, the crude rates are identical since the reference population is irrelevant for those calculations (53.51 vs 53.51). However, the age-standardized rates changed from 51.93 to 53.34. Remember, if you want to compare your age-adjusted rates to those published by other health jurisdictions, it’s important that you use the same reference population.</p>
<hr />
<h2 id="example-2-stratifcation">Example #2: Stratifcation</h2>
<p><strong>Let’s create a new dataset with disease counts aggregated by age (46 to 64) and gender (F|M)</strong></p>
<pre><code class="language-r">set.seed(98121)
temp2 &lt;- data.table(
  gender = c(rep(&quot;F&quot;, 20), rep(&quot;M&quot;, 20)), 
  age = rep(46:65, 2),
  disease = c(sample(25:46, 20, replace = T), sample(25:35, 20, replace = T)), 
  pop = c(sample(2500:3500, 20, replace = T), sample(2200:3300, 20, replace = T)))

head(temp2)
</code></pre>
<pre><code>##    gender age disease  pop
## 1:      F  46      32 3134
## 2:      F  47      36 2930
## 3:      F  48      29 3289
## 4:      F  49      27 3198
## 5:      F  50      27 3480
## 6:      F  51      33 2679
</code></pre>
<p><strong>Let’s examine the overall rates</strong></p>
<pre><code class="language-r">ex2.1 &lt;- age_standardize(ph.data = temp2,
                       collapse = T,
                       my.count = &quot;disease&quot;, 
                       my.pop = &quot;pop&quot;, 
                       per = 1000, 
                       conf.level = 0.95)

ex2.1[]
</code></pre>
<pre><code>##    count    pop crude.rate crude.lci crude.uci adj.rate adj.lci adj.uci
## 1:  1333 115448      11.55     10.93     12.18    11.68   10.87   12.57
##                               reference_pop
## 1: 2000 U.S. Std Population (11 age groups)
</code></pre>
<p>In this case, the crude rate and age standardized rate are the same. This doesn’t mean there is a mistake. Notice that the confidence intervals differ – as would be expected.</p>
<p>Also notice that we didn’t include the <code>ref.popname</code> argument. When it is not specified, <code>age_standardize()</code> uses the default which is <code>list_ref_pop()[1]</code> (i.e, 2000 U.S. Std Population (11 age groups)).</p>
<p><strong>Now let’s run the same analysis, but stratified by gender</strong></p>
<pre><code class="language-r">ex2.2 &lt;- age_standardize(ph.data = temp2,
                       collapse = T,
                       my.count = &quot;disease&quot;, 
                       my.pop = &quot;pop&quot;, 
                       per = 1000, 
                       conf.level = 0.95, 
                       group_by = &quot;gender&quot;)

ex2.2[]
</code></pre>
<pre><code>##    gender count   pop crude.rate crude.lci crude.uci adj.rate adj.lci adj.uci
## 1:      F   731 60827      12.02     11.16     12.92    12.22   11.07   13.50
## 2:      M   602 54621      11.02     10.16     11.94    11.09    9.97   12.36
##                               reference_pop
## 1: 2000 U.S. Std Population (11 age groups)
## 2: 2000 U.S. Std Population (11 age groups)
</code></pre>
<p>Here we see that the crude and age standardized rates are higher among females when compared to males.</p>
<hr />
<h2 id="example-3-using-your-own-standard-population">Example #3: Using your own standard population</h2>
<p><strong>Create a reference population for the gendered dataset above</strong></p>
<p>To keep things simple, we will create a reference population based on single ages rather than age bins. As specified in the arguments description above, we will name the standard population column ‘stdpop’.</p>
<pre><code class="language-r">set.seed(98121)
new.standard &lt;- data.table(
  gender = c(rep(&quot;M&quot;, 20), rep(&quot;F&quot;, 20)), 
  age = rep(46:65, 2),
  stdpop = c(sample(7800:16000, 20, replace = T), sample(10000:20000, 20, replace = T)))

head(new.standard)
</code></pre>
<pre><code>##    gender age stdpop
## 1:      M  46  10160
## 2:      M  47   8515
## 3:      M  48   9204
## 4:      M  49   7827
## 5:      M  50   9756
## 6:      M  51   9178
</code></pre>
<p><strong>Merge the standard population onto the data</strong></p>
<pre><code class="language-r">temp3 &lt;- merge(temp2, new.standard, by = c(&quot;age&quot;, &quot;gender&quot;), all = T)

head(temp3)
</code></pre>
<pre><code>##    age gender disease  pop stdpop
## 1:  46      F      32 3134  14506
## 2:  46      M      26 3055  10160
## 3:  47      F      36 2930  18955
## 4:  47      M      35 2954   8515
## 5:  48      F      29 3289  17813
## 6:  48      M      35 2268   9204
</code></pre>
<p><strong>Calculate the rates when <code>ref.pop = &quot;none&quot;</code></strong></p>
<p>Note that I need to specify <code>collapse = F</code> because the function expects data to be pre-aggregated for the custom reference population contained in <code>stdpop</code>.</p>
<pre><code class="language-r">ex3.1 &lt;- age_standardize(ph.data = temp3,
                       ref.popname = &quot;none&quot;,
                       collapse = F,
                       my.count = &quot;disease&quot;, 
                       my.pop = &quot;pop&quot;, 
                       per = 1000, 
                       conf.level = 0.95, 
                       group_by = &quot;gender&quot;)

ex3.1[]
</code></pre>
<pre><code>##    gender count   pop crude.rate crude.lci crude.uci adj.rate adj.lci adj.uci
## 1:      F   731 60827      12.02     11.16     12.92    12.02   11.15   12.95
## 2:      M   602 54621      11.02     10.16     11.94    11.15   10.25   12.12
##               reference_pop
## 1: stdpop column in `temp3`
## 2: stdpop column in `temp3`
</code></pre>
<hr />
<h2 id="example-4-when-to-specify-collapse-f">Example #4: When to specify <code>collapse = F</code></h2>
<p>In example #3 above, we specified <code>collapse = F</code> because <code>age_standardardize()</code> expects the data to be pre-aggregated when you provide a <code>stdpop</code> column. The other time when you will want to set <code>collapse = F</code> is if you have data that has already been collapsed down to the reference population’s age bins along with the proper labels in a column called <code>agecat</code>. <strong>This is uncommon.</strong> It isn’t worth your time and energy to manually collapse the data – so don’t do it! This functionality is here just in case you receive data that has already been structured this way.</p>
<p><strong>Let’s recreate the dataset used in example 2 above</strong></p>
<pre><code class="language-r">set.seed(98121)
temp4 &lt;- data.table(
  gender = c(rep(&quot;M&quot;, 20), rep(&quot;F&quot;, 20)), 
  age = rep(46:65, 2),
  disease = c(sample(25:46, 20, replace = T), sample(25:35, 20, replace = T)), 
  pop = c(sample(2500:3500, 20, replace = T), sample(2200:3300, 20, replace = T)))

head(temp4)
</code></pre>
<pre><code>##    gender age disease  pop
## 1:      M  46      32 3134
## 2:      M  47      36 2930
## 3:      M  48      29 3289
## 4:      M  49      27 3198
## 5:      M  50      27 3480
## 6:      M  51      33 2679
</code></pre>
<p><strong>Collapse the data down to the same age bins as those used in the APDE standard reference population</strong></p>
<pre><code class="language-r">temp4[age %in% 45:49, agecat := &quot;45-49 years&quot;]
temp4[age %in% 50:54, agecat := &quot;50-54 years&quot;]
temp4[age %in% 55:59, agecat := &quot;55-59 years&quot;]
temp4[age %in% 60:64, agecat := &quot;60-64 years&quot;]
temp4[age %in% 65:69, agecat := &quot;65-69 years&quot;]
temp4 &lt;- temp4[, .(pop = sum(pop), disease = sum(disease)), by = c(&quot;agecat&quot;, &quot;gender&quot;)]

temp4[]
</code></pre>
<pre><code>##          agecat gender   pop disease
##  1: 45-49 years      M 12551     124
##  2: 50-54 years      M 15192     169
##  3: 55-59 years      M 15466     198
##  4: 60-64 years      M 14425     194
##  5: 65-69 years      M  3193      46
##  6: 45-49 years      F 11302     130
##  7: 50-54 years      F 13392     149
##  8: 55-59 years      F 12631     159
##  9: 60-64 years      F 14498     133
## 10: 65-69 years      F  2798      31
</code></pre>
<p><strong>Now you are able to run age_standardize with <code>collapse = F</code></strong></p>
<pre><code class="language-r">ex4.1 &lt;- age_standardize(ph.data = temp4,
                       collapse = F,
                       my.count = &quot;disease&quot;, 
                       my.pop = &quot;pop&quot;, 
                       per = 1000, 
                       conf.level = 0.95, 
                       group_by = &quot;gender&quot;)

ex4.1[]
</code></pre>
<pre><code>## Empty data.table (0 rows and 10 cols): gender,count,pop,crude.rate,crude.lci,crude.uci...
</code></pre>
<p>Note the results in ex4.1 are exactly the same as those in ex2.2. This makes sense since <code>age_standardize()</code> collapsed the data in a similar (but more efficient manner) when creating ex2.2.</p>
<hr />
<h2 id="example-5-real-world-analysis">Example #5: Real world analysis</h2>
<p>You’re staffing data requests today and receive the following message: “<em>Hi! For a class, I’d like to get the 2019 teen (13 to 19) birth rate for King County and WA State as a whole. Since the age distribution in the county may differ from the rest of the state, it would be appreciated if you could provide crude and age-standardized rates. If you could standardize to “World (WHO 2000-2025) Std Million (single ages to 84)”, that would be great! Thank you, S. Capstone</em>”</p>
<p>You quickly pull up <a href="https://www.doh.wa.gov/ForPublicHealthandHealthcareProviders/PublicHealthSystemResourcesandServices/CommunityHealthAssessmentandImprovement/CHAT">CHAT</a> only to find that this specific indicator doesn’t exist. You remember that <a href="https://kingcounty.gov/chi/">CHI</a> has an adolescent birth rate indicator, but are downcast when you find that it applies to those 15 to 17. In desperation, you resign yourself to using <code>rads</code>.</p>
<p><strong>Get birth counts for 13 to 19 year olds in 2019</strong></p>
<pre><code class="language-r">  kcbirth &lt;- get_data_birth(cols = c(&quot;chi_age&quot;, &quot;chi_year&quot;), year = 2019, kingco = T)
  wabirth &lt;- get_data_birth(cols = c(&quot;chi_age&quot;, &quot;chi_year&quot;), year = 2019, kingco = F)
  
  births &lt;- rbind(kcbirth[, geo := &quot;King County&quot;], wabirth[, geo := &quot;WA State&quot;])
  births &lt;- births[chi_age %in% 13:19]
  
  # collapse / aggregate
  births &lt;- births[, .(births = .N), by = c(&quot;chi_age&quot;, &quot;geo&quot;)] 
  setorder(births, geo, chi_age)
  setnames(births, &quot;chi_age&quot;, &quot;age&quot;)
  births[]
</code></pre>
<pre><code>##     age         geo births
##  1:  13 King County      1
##  2:  14 King County      4
##  3:  15 King County     10
##  4:  16 King County     23
##  5:  17 King County     45
##  6:  18 King County    107
##  7:  19 King County    230
##  8:  13    WA State      6
##  9:  14    WA State     16
## 10:  15    WA State     70
## 11:  16    WA State    193
## 12:  17    WA State    346
## 13:  18    WA State    745
## 14:  19    WA State   1488
</code></pre>
<p><strong>Get the female populations corresponding to the birth counts</strong></p>
<pre><code class="language-r">  kcpop &lt;- get_population(kingco = T, years = 2019, ages = 13:19, 
                          genders = &quot;Female&quot;, group_by = &quot;ages&quot;, geo_vintage = 2020, census_vintage = 2020)
  kcpop &lt;- kcpop[, .(age, geo = geo_id, pop)] 
  
  wapop &lt;- get_population(kingco = F, years = 2019, ages = 13:19, 
                          genders = &quot;Female&quot;, group_by = &quot;ages&quot;, geo_type = &quot;zip&quot;, geo_vintage = 2020, census_vintage = 2020)
  wapop &lt;- wapop[, .(pop = sum(pop), geo = &quot;WA State&quot;), by = &quot;age&quot;]
  
  pop &lt;- rbind(kcpop, wapop)
  pop[]
</code></pre>
<pre><code>##     age         geo      pop
##  1:  18 King County 12654.47
##  2:  19 King County 13401.31
##  3:  13 King County 12407.25
##  4:  15 King County 11131.42
##  5:  16 King County 11420.94
##  6:  17 King County 11565.07
##  7:  14 King County 12208.96
##  8:  18    WA State 45951.20
##  9:  16    WA State 44581.08
## 10:  17    WA State 43452.42
## 11:  14    WA State 46476.42
## 12:  13    WA State 46374.96
## 13:  19    WA State 47390.04
## 14:  15    WA State 44635.30
</code></pre>
<p><strong>Merge population onto to birth counts</strong></p>
<pre><code class="language-r">  temp5 &lt;- merge(births, pop, by = c(&quot;age&quot;, &quot;geo&quot;), all = T)
  
  temp5[]
</code></pre>
<pre><code>##     age         geo births      pop
##  1:  13 King County      1 12407.25
##  2:  13    WA State      6 46374.96
##  3:  14 King County      4 12208.96
##  4:  14    WA State     16 46476.42
##  5:  15 King County     10 11131.42
##  6:  15    WA State     70 44635.30
##  7:  16 King County     23 11420.94
##  8:  16    WA State    193 44581.08
##  9:  17 King County     45 11565.07
## 10:  17    WA State    346 43452.42
## 11:  18 King County    107 12654.47
## 12:  18    WA State    745 45951.20
## 13:  19 King County    230 13401.31
## 14:  19    WA State   1488 47390.04
</code></pre>
<p><strong>Run <code>age_standardize()</code></strong></p>
<pre><code class="language-r">  ex5.1 &lt;- age_standardize(ph.data = temp5,
                           ref.popname = &quot;World (WHO 2000-2025) Std Million (single ages to 84)&quot;, 
                           collapse = T,
                           my.count = &quot;births&quot;, 
                           my.pop = &quot;pop&quot;, 
                           per = 1000, 
                           conf.level = 0.95, 
                           group_by = &quot;geo&quot;)
  ex5.1[]
</code></pre>
<pre><code>##            geo count       pop crude.rate crude.lci crude.uci adj.rate adj.lci
## 1: King County   420  84789.41       4.95      4.49      5.45     4.65    4.21
## 2:    WA State  2864 318861.42       8.98      8.66      9.32     8.77    8.45
##    adj.uci                                         reference_pop
## 1:    5.12 World (WHO 2000-2025) Std Million (single ages to 84)
## 2:    9.10 World (WHO 2000-2025) Std Million (single ages to 84)
</code></pre>
<p>According to your analysis, the crude King County teen birth rate is approximately half (4.95 / 8.98 = 0.551) of the WA State teen birth rate. This relationship remains largely unchanged after age-standardization  (4.65 / 8.77 = 0.53).</p>
<hr />
<h2 id="conclusion">Conclusion</h2>
<p>If you’ve walked through this vignette and more or less understood what’s going on, you’re in good shape! If you’re still confused, please walk through it again and then reach out if you still have questions. Good luck!</p>
</div>
<div class="include-after">
</div>
<script src="https://cdn.jsdelivr.net/npm/prismjs@1.29.0/components/prism-core.min.js" defer></script>
<script src="https://cdn.jsdelivr.net/npm/prismjs@1.29.0/plugins/autoloader/prism-autoloader.min.js" defer></script>
</body>
</html>
