<!DOCTYPE html>

<html>

<head>

<meta charset="utf-8" />
<meta name="generator" content="pandoc" />
<meta http-equiv="X-UA-Compatible" content="IE=EDGE" />

<meta name="viewport" content="width=device-width, initial-scale=1" />



<title>calc()</title>

<script>// Pandoc 2.9 adds attributes on both header and div. We remove the former (to
// be compatible with the behavior of Pandoc < 2.8).
document.addEventListener('DOMContentLoaded', function(e) {
  var hs = document.querySelectorAll("div.section[class*='level'] > :first-child");
  var i, h, a;
  for (i = 0; i < hs.length; i++) {
    h = hs[i];
    if (!/^h[1-6]$/i.test(h.tagName)) continue;  // it should be a header h1-h6
    a = h.attributes;
    while (a.length > 0) h.removeAttribute(a[0].name);
  }
});
</script>

<style type="text/css">
  code{white-space: pre-wrap;}
  span.smallcaps{font-variant: small-caps;}
  span.underline{text-decoration: underline;}
  div.column{display: inline-block; vertical-align: top; width: 50%;}
  div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
  ul.task-list{list-style: none;}
    </style>


<style type="text/css">
  code {
    white-space: pre;
  }
  .sourceCode {
    overflow: visible;
  }
</style>
<style type="text/css" data-origin="pandoc">
pre > code.sourceCode { white-space: pre; position: relative; }
pre > code.sourceCode > span { display: inline-block; line-height: 1.25; }
pre > code.sourceCode > span:empty { height: 1.2em; }
.sourceCode { overflow: visible; }
code.sourceCode > span { color: inherit; text-decoration: inherit; }
div.sourceCode { margin: 1em 0; }
pre.sourceCode { margin: 0; }
@media screen {
div.sourceCode { overflow: auto; }
}
@media print {
pre > code.sourceCode { white-space: pre-wrap; }
pre > code.sourceCode > span { text-indent: -5em; padding-left: 5em; }
}
pre.numberSource code
  { counter-reset: source-line 0; }
pre.numberSource code > span
  { position: relative; left: -4em; counter-increment: source-line; }
pre.numberSource code > span > a:first-child::before
  { content: counter(source-line);
    position: relative; left: -1em; text-align: right; vertical-align: baseline;
    border: none; display: inline-block;
    -webkit-touch-callout: none; -webkit-user-select: none;
    -khtml-user-select: none; -moz-user-select: none;
    -ms-user-select: none; user-select: none;
    padding: 0 4px; width: 4em;
    color: #aaaaaa;
  }
pre.numberSource { margin-left: 3em; border-left: 1px solid #aaaaaa;  padding-left: 4px; }
div.sourceCode
  {   }
@media screen {
pre > code.sourceCode > span > a:first-child::before { text-decoration: underline; }
}
code span.al { color: #ff0000; font-weight: bold; } /* Alert */
code span.an { color: #60a0b0; font-weight: bold; font-style: italic; } /* Annotation */
code span.at { color: #7d9029; } /* Attribute */
code span.bn { color: #40a070; } /* BaseN */
code span.bu { } /* BuiltIn */
code span.cf { color: #007020; font-weight: bold; } /* ControlFlow */
code span.ch { color: #4070a0; } /* Char */
code span.cn { color: #880000; } /* Constant */
code span.co { color: #60a0b0; font-style: italic; } /* Comment */
code span.cv { color: #60a0b0; font-weight: bold; font-style: italic; } /* CommentVar */
code span.do { color: #ba2121; font-style: italic; } /* Documentation */
code span.dt { color: #902000; } /* DataType */
code span.dv { color: #40a070; } /* DecVal */
code span.er { color: #ff0000; font-weight: bold; } /* Error */
code span.ex { } /* Extension */
code span.fl { color: #40a070; } /* Float */
code span.fu { color: #06287e; } /* Function */
code span.im { } /* Import */
code span.in { color: #60a0b0; font-weight: bold; font-style: italic; } /* Information */
code span.kw { color: #007020; font-weight: bold; } /* Keyword */
code span.op { color: #666666; } /* Operator */
code span.ot { color: #007020; } /* Other */
code span.pp { color: #bc7a00; } /* Preprocessor */
code span.sc { color: #4070a0; } /* SpecialChar */
code span.ss { color: #bb6688; } /* SpecialString */
code span.st { color: #4070a0; } /* String */
code span.va { color: #19177c; } /* Variable */
code span.vs { color: #4070a0; } /* VerbatimString */
code span.wa { color: #60a0b0; font-weight: bold; font-style: italic; } /* Warning */

</style>
<script>
// apply pandoc div.sourceCode style to pre.sourceCode instead
(function() {
  var sheets = document.styleSheets;
  for (var i = 0; i < sheets.length; i++) {
    if (sheets[i].ownerNode.dataset["origin"] !== "pandoc") continue;
    try { var rules = sheets[i].cssRules; } catch (e) { continue; }
    for (var j = 0; j < rules.length; j++) {
      var rule = rules[j];
      // check if there is a div.sourceCode rule
      if (rule.type !== rule.STYLE_RULE || rule.selectorText !== "div.sourceCode") continue;
      var style = rule.style.cssText;
      // check if color or background-color is set
      if (rule.style.color === '' && rule.style.backgroundColor === '') continue;
      // replace div.sourceCode by a pre.sourceCode rule
      sheets[i].deleteRule(j);
      sheets[i].insertRule('pre.sourceCode{' + style + '}', j);
    }
  }
})();
</script>




<style type="text/css">body {
background-color: #fff;
margin: 1em auto;
max-width: 700px;
overflow: visible;
padding-left: 2em;
padding-right: 2em;
font-family: "Open Sans", "Helvetica Neue", Helvetica, Arial, sans-serif;
font-size: 14px;
line-height: 1.35;
}
#TOC {
clear: both;
margin: 0 0 10px 10px;
padding: 4px;
width: 400px;
border: 1px solid #CCCCCC;
border-radius: 5px;
background-color: #f6f6f6;
font-size: 13px;
line-height: 1.3;
}
#TOC .toctitle {
font-weight: bold;
font-size: 15px;
margin-left: 5px;
}
#TOC ul {
padding-left: 40px;
margin-left: -1.5em;
margin-top: 5px;
margin-bottom: 5px;
}
#TOC ul ul {
margin-left: -2em;
}
#TOC li {
line-height: 16px;
}
table {
margin: 1em auto;
border-width: 1px;
border-color: #DDDDDD;
border-style: outset;
border-collapse: collapse;
}
table th {
border-width: 2px;
padding: 5px;
border-style: inset;
}
table td {
border-width: 1px;
border-style: inset;
line-height: 18px;
padding: 5px 5px;
}
table, table th, table td {
border-left-style: none;
border-right-style: none;
}
table thead, table tr.even {
background-color: #f7f7f7;
}
p {
margin: 0.5em 0;
}
blockquote {
background-color: #f6f6f6;
padding: 0.25em 0.75em;
}
hr {
border-style: solid;
border: none;
border-top: 1px solid #777;
margin: 28px 0;
}
dl {
margin-left: 0;
}
dl dd {
margin-bottom: 13px;
margin-left: 13px;
}
dl dt {
font-weight: bold;
}
ul {
margin-top: 0;
}
ul li {
list-style: circle outside;
}
ul ul {
margin-bottom: 0;
}
pre, code {
background-color: #f7f7f7;
border-radius: 3px;
color: #333;
white-space: pre-wrap; 
}
pre {
border-radius: 3px;
margin: 5px 0px 10px 0px;
padding: 10px;
}
pre:not([class]) {
background-color: #f7f7f7;
}
code {
font-family: Consolas, Monaco, 'Courier New', monospace;
font-size: 85%;
}
p > code, li > code {
padding: 2px 0px;
}
div.figure {
text-align: center;
}
img {
background-color: #FFFFFF;
padding: 2px;
border: 1px solid #DDDDDD;
border-radius: 3px;
border: 1px solid #CCCCCC;
margin: 0 5px;
}
h1 {
margin-top: 0;
font-size: 35px;
line-height: 40px;
}
h2 {
border-bottom: 4px solid #f7f7f7;
padding-top: 10px;
padding-bottom: 2px;
font-size: 145%;
}
h3 {
border-bottom: 2px solid #f7f7f7;
padding-top: 10px;
font-size: 120%;
}
h4 {
border-bottom: 1px solid #f7f7f7;
margin-left: 8px;
font-size: 105%;
}
h5, h6 {
border-bottom: 1px solid #ccc;
font-size: 105%;
}
a {
color: #0033dd;
text-decoration: none;
}
a:hover {
color: #6666ff; }
a:visited {
color: #800080; }
a:visited:hover {
color: #BB00BB; }
a[href^="http:"] {
text-decoration: underline; }
a[href^="https:"] {
text-decoration: underline; }

code > span.kw { color: #555; font-weight: bold; } 
code > span.dt { color: #902000; } 
code > span.dv { color: #40a070; } 
code > span.bn { color: #d14; } 
code > span.fl { color: #d14; } 
code > span.ch { color: #d14; } 
code > span.st { color: #d14; } 
code > span.co { color: #888888; font-style: italic; } 
code > span.ot { color: #007020; } 
code > span.al { color: #ff0000; font-weight: bold; } 
code > span.fu { color: #900; font-weight: bold; } 
code > span.er { color: #a61717; background-color: #e3d2d2; } 
</style>




</head>

<body>




<h1 class="title toc-ignore">calc()</h1>



<div id="introduction" class="section level2">
<h2>Introduction</h2>
<p><code>calc()</code> is the analytic workhorse of <code>rads</code>.
It provides a standardized method for obtaining most of what we usually
want to calculate: means, medians, counts, confidence intervals,
standard errors, relative standard errors (RSE), numerators,
denominators, the number missing, and the proportion missing.
<code>calc()</code> can be used with record data (e.g., vital
statistics, census, enrollment numbers, etc.) as well as survey data
(e.g., <a href="https://www.cdc.gov/brfss/index.html">BRFSS</a>, <a href="https://github.com/PHSKC-APDE/svy_acs">ACS PUMS</a>, etc.).
<code>calc()</code> is built on top of common R packages and was created
to allow APDE staff the convenience of using a common syntax across
various data sources. This means that everything <code>calc</code> can
do can be done with other packages … sometimes in a more efficient
manner.</p>
<p>This vignette will provide some examples to introduce the
<code>calc()</code> function by walking through basic analyses with
vital statistics (birth data) and survey data (ACS PUMS). To get the
most out of this vignette, we recommend that you type each and every bit
of code into R. Doing so will almost definitely help you learn the
syntax much faster than just reading the vignette or copying and pasting
the code.</p>
</div>
<div id="calc-arguments" class="section level2">
<h2><code>calc()</code> arguments</h2>
<p>Arguments are the values that we send to a function when it is
called. The standard arguments for <code>calc()</code> are:</p>
<p>1) <code>ph.data</code> &lt;- the name of the data.table/data.frame
or survey object that you want to analyze.</p>
<p>2) <code>what</code> &lt;- a character vector of the variable(s) for
which you want to calculate the metrics. E.g.,
<code>what = c(&quot;uninsured&quot;)</code></p>
<p>3) <code>where</code> &lt;- think of this as a SQL <code>WHERE</code>
clause, i.e., a filtering or subsetting of data. E.g.,
<code>ages %in% c(0:17) &amp; gender == &quot;Female&quot;</code></p>
<p>4) <code>by</code> &lt;- a character vector of the variables that you
want to computer the <code>what</code> by, i.e., the cross-tab
variable(s). E.g., <code>by = c(&quot;gender&quot;)</code> would stratify results
by gender</p>
<p>5) <code>metrics</code> &lt;- a character vector of the metrics that
you want returned. E.g., <code>metrics = c(&quot;mean&quot;, &quot;rse&quot;)</code>. You
can see a complete list of available metrics by typing
<code>metrics()</code> and get detailed descriptions of what each metric
means by typing <code>?metrics()</code>.</p>
<p>6) <code>per</code> &lt;- an integer, which is the denominator when
<code>rate</code> is selected as a metric. Metrics will be multiplied by
this value. E.g., <code>per = 1000</code>. <strong>NOTE</strong> this is
just a scalar. At present this does not calculate a true rate (i.e., the
relevant population denominator is not used).</p>
<p>7) <code>win</code> &lt;- an integer, which is the number of
consecutive units of time (e.g., years, months, etc.) over which the
metrics will be calculated, i.e., the ‘window’ for a rolling average,
sum, etc. E.g. <code>win = 5</code> will perform calculations over every
5 time unit window.</p>
<p>8) <code>time_var</code> &lt;- a character, which is the name of the
time variable in the dataset. Used in combination with the
<code>win</code> argument to generate time windowed calculations.</p>
<p>9) <code>fancy_time</code> &lt;- a logical (i.e., <code>T</code> or
<code>F</code>) flag. If TRUE, a record of all the years going into the
data is returned. If FALSE, just a simple range (where certain years
within the range might not be represented in your data).</p>
<p>10) <code>proportion</code> &lt;- a logical (i.e., <code>T</code> or
<code>F</code>) flag determining whether the metrics should be
calculated as a proportion. Currently only relevant for survey data. The
default is FALSE.</p>
<p>11) <code>ci</code> &lt;- a numeric value between 0 &amp; 1 for the
confidence level returned in the estimates. E.g., 0.95 == 95% confidence
interval</p>
<p>12) <code>verbose</code> &lt;- a logical used to toggle on/off
printed warnings</p>
<p>There is no need to specify all of the arguments listed above. As you
can see in the following example, the <code>calc</code> function simply
needs a specified dataset (i.e., <code>ph.data</code>) and at least one
<code>what</code> variable to return an intelligible result.</p>
<div class="sourceCode" id="cb1"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb1-1"><a href="#cb1-1" aria-hidden="true" tabindex="-1"></a><span class="fu">data</span>(mtcars)</span>
<span id="cb1-2"><a href="#cb1-2" aria-hidden="true" tabindex="-1"></a>mtcars <span class="ot">=</span> <span class="fu">dtadmin</span>(mtcars) <span class="co">#make it work with calc.dtsurvey</span></span>
<span id="cb1-3"><a href="#cb1-3" aria-hidden="true" tabindex="-1"></a><span class="fu">calc</span>(<span class="at">ph.data =</span> mtcars, <span class="at">what =</span> <span class="fu">c</span>(<span class="st">&quot;mpg&quot;</span>))[]</span></code></pre></div>
<pre><code>##    variable     mean numerator denominator level  mean_se mean_lower mean_upper
## 1:      mpg 20.09062     642.9          32    NA 1.065424   18.00243   22.17882</code></pre>
<p><strong>Note:</strong> <em>The use of <code>[]</code> after
<code>calc()</code> is used to print the output to the console.
Typically, you would not print the results but would save them as an
object. E.g., <code>my.est &lt;- calc()</code>.</em></p>
<hr />
</div>
<div id="example-vital-statistics-analyses" class="section level2">
<h2>Example vital statistics analyses</h2>
<p><strong>First get the birth data (cf. <a href="https://github.com/PHSKC-APDE/rads/wiki/get_data">get_data
vignette</a>)</strong></p>
<div class="sourceCode" id="cb3"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb3-1"><a href="#cb3-1" aria-hidden="true" tabindex="-1"></a>birth <span class="ot">&lt;-</span> <span class="fu">get_data_birth</span>(<span class="at">cols =</span> <span class="fu">c</span>(<span class="st">&quot;chi_year&quot;</span>, <span class="st">&quot;chi_sex&quot;</span>, <span class="st">&quot;chi_race_eth8&quot;</span>, </span>
<span id="cb3-2"><a href="#cb3-2" aria-hidden="true" tabindex="-1"></a>                                 <span class="st">&quot;preterm&quot;</span>, <span class="st">&quot;birth_weight_grams&quot;</span>, <span class="st">&quot;mother_birthplace_state&quot;</span>), </span>
<span id="cb3-3"><a href="#cb3-3" aria-hidden="true" tabindex="-1"></a>                        <span class="at">year =</span> <span class="fu">c</span>(<span class="dv">2013</span><span class="sc">:</span><span class="dv">2019</span>), </span>
<span id="cb3-4"><a href="#cb3-4" aria-hidden="true" tabindex="-1"></a>                        <span class="at">kingco =</span> T)</span></code></pre></div>
<p><strong>mean (proportion) for a binary over multiple
years</strong></p>
<div class="sourceCode" id="cb4"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb4-1"><a href="#cb4-1" aria-hidden="true" tabindex="-1"></a><span class="fu">calc</span>(<span class="at">ph.data =</span> birth, </span>
<span id="cb4-2"><a href="#cb4-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">what =</span> <span class="fu">c</span>(<span class="st">&quot;preterm&quot;</span>), </span>
<span id="cb4-3"><a href="#cb4-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">metrics =</span> <span class="fu">c</span>(<span class="st">&quot;mean&quot;</span>, <span class="st">&quot;rse&quot;</span>, <span class="st">&quot;numerator&quot;</span>, <span class="st">&quot;denominator&quot;</span>), </span>
<span id="cb4-4"><a href="#cb4-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">time_var =</span> <span class="st">&quot;chi_year&quot;</span>)[]</span></code></pre></div>
<pre><code>##     chi_year variable       mean numerator denominator level      mean_se
## 1: 2013-2019  preterm 0.09052329     15806      174607    NA 0.0006866673
##    mean_lower mean_upper       rse
## 1: 0.08917745 0.09186913 0.7585532</code></pre>
<p><strong>mean (proportion) for a binary over multiple years –
<code>where</code> newborn is male</strong></p>
<div class="sourceCode" id="cb6"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb6-1"><a href="#cb6-1" aria-hidden="true" tabindex="-1"></a><span class="fu">calc</span>(<span class="at">ph.data =</span> birth, </span>
<span id="cb6-2"><a href="#cb6-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">what =</span> <span class="fu">c</span>(<span class="st">&quot;preterm&quot;</span>), </span>
<span id="cb6-3"><a href="#cb6-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">where =</span> chi_sex <span class="sc">==</span> <span class="st">&quot;Male&quot;</span>,</span>
<span id="cb6-4"><a href="#cb6-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">metrics =</span> <span class="fu">c</span>(<span class="st">&quot;mean&quot;</span>, <span class="st">&quot;rse&quot;</span>, <span class="st">&quot;numerator&quot;</span>, <span class="st">&quot;denominator&quot;</span>), </span>
<span id="cb6-5"><a href="#cb6-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">time_var =</span> <span class="st">&quot;chi_year&quot;</span>)[]</span></code></pre></div>
<pre><code>##     chi_year variable       mean numerator denominator level      mean_se
## 1: 2013-2019  preterm 0.09716898      8694       89473    NA 0.0009902013
##    mean_lower mean_upper      rse
## 1: 0.09522822 0.09910974 1.019051</code></pre>
<p><strong>mean (proportion) for a binary over multiple years –
<code>where</code> newborn is male born to a Hispanic
mother</strong></p>
<div class="sourceCode" id="cb8"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb8-1"><a href="#cb8-1" aria-hidden="true" tabindex="-1"></a><span class="fu">calc</span>(<span class="at">ph.data =</span> birth, </span>
<span id="cb8-2"><a href="#cb8-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">what =</span> <span class="fu">c</span>(<span class="st">&quot;preterm&quot;</span>), </span>
<span id="cb8-3"><a href="#cb8-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">where =</span> chi_sex <span class="sc">==</span> <span class="st">&quot;Male&quot;</span> <span class="sc">&amp;</span> chi_race_eth8 <span class="sc">==</span> <span class="st">&quot;Hispanic&quot;</span>,</span>
<span id="cb8-4"><a href="#cb8-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">metrics =</span> <span class="fu">c</span>(<span class="st">&quot;mean&quot;</span>, <span class="st">&quot;rse&quot;</span>, <span class="st">&quot;numerator&quot;</span>, <span class="st">&quot;denominator&quot;</span>), </span>
<span id="cb8-5"><a href="#cb8-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">time_var =</span> <span class="st">&quot;chi_year&quot;</span>)[]</span></code></pre></div>
<pre><code>##     chi_year variable      mean numerator denominator level     mean_se
## 1: 2013-2019  preterm 0.1105628      1277       11550    NA 0.002918031
##    mean_lower mean_upper      rse
## 1:  0.1048435   0.116282 2.639253</code></pre>
<p><strong>mean (proportion) for a binary over individual
years</strong></p>
<div class="sourceCode" id="cb10"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb10-1"><a href="#cb10-1" aria-hidden="true" tabindex="-1"></a>birth[, cy <span class="sc">:</span><span class="er">=</span> chi_year]</span>
<span id="cb10-2"><a href="#cb10-2" aria-hidden="true" tabindex="-1"></a><span class="fu">calc</span>(<span class="at">ph.data =</span> birth, </span>
<span id="cb10-3"><a href="#cb10-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">what =</span> <span class="fu">c</span>(<span class="st">&quot;preterm&quot;</span>), </span>
<span id="cb10-4"><a href="#cb10-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">metrics =</span> <span class="fu">c</span>(<span class="st">&quot;mean&quot;</span>, <span class="st">&quot;rse&quot;</span>, <span class="st">&quot;numerator&quot;</span>, <span class="st">&quot;denominator&quot;</span>), </span>
<span id="cb10-5"><a href="#cb10-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">time_var =</span> <span class="st">&quot;chi_year&quot;</span>, </span>
<span id="cb10-6"><a href="#cb10-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">by =</span> <span class="st">&quot;cy&quot;</span>)[]</span></code></pre></div>
<pre><code>##      cy chi_year variable       mean numerator denominator level     mean_se
## 1: 2013     2013  preterm 0.09259783      2293       24763    NA 0.001842076
## 2: 2014     2014  preterm 0.08847557      2231       25216    NA 0.001788407
## 3: 2015     2015  preterm 0.08829787      2241       25380    NA 0.001781002
## 4: 2016     2016  preterm 0.08956837      2320       25902    NA 0.001774364
## 5: 2017     2017  preterm 0.09120521      2296       25174    NA 0.001814576
## 6: 2018     2018  preterm 0.08944869      2166       24215    NA 0.001834028
## 7: 2019     2019  preterm 0.09429394      2259       23957    NA 0.001888115
##    mean_lower mean_upper      rse
## 1: 0.08898743 0.09620823 1.989329
## 2: 0.08497036 0.09198078 2.021357
## 3: 0.08480717 0.09178857 2.017038
## 4: 0.08609068 0.09304606 1.981016
## 5: 0.08764871 0.09476172 1.989553
## 6: 0.08585406 0.09304332 2.050369
## 7: 0.09059331 0.09799458 2.002371</code></pre>
<p><strong>mean (proportion) for a binary over windowed
years</strong></p>
<div class="sourceCode" id="cb12"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb12-1"><a href="#cb12-1" aria-hidden="true" tabindex="-1"></a><span class="fu">calc</span>(<span class="at">ph.data =</span> birth, </span>
<span id="cb12-2"><a href="#cb12-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">what =</span> <span class="fu">c</span>(<span class="st">&quot;preterm&quot;</span>), </span>
<span id="cb12-3"><a href="#cb12-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">metrics =</span> <span class="fu">c</span>(<span class="st">&quot;mean&quot;</span>, <span class="st">&quot;rse&quot;</span>, <span class="st">&quot;numerator&quot;</span>, <span class="st">&quot;denominator&quot;</span>), </span>
<span id="cb12-4"><a href="#cb12-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">time_var =</span> <span class="st">&quot;chi_year&quot;</span>, </span>
<span id="cb12-5"><a href="#cb12-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">win =</span> <span class="dv">3</span>)[]</span></code></pre></div>
<pre><code>##     chi_year variable       mean numerator denominator level     mean_se
## 1: 2013-2015  preterm 0.08977030      6765       75359    NA 0.001041303
## 2: 2014-2016  preterm 0.08878663      6792       76498    NA 0.001028399
## 3: 2015-2017  preterm 0.08968557      6857       76456    NA 0.001033366
## 4: 2016-2018  preterm 0.09007717      6782       75291    NA 0.001043376
## 5: 2017-2019  preterm 0.09163417      6721       73346    NA 0.001065305
##    mean_lower mean_upper      rse
## 1: 0.08772938 0.09181122 1.159964
## 2: 0.08677101 0.09080226 1.158281
## 3: 0.08766021 0.09171093 1.152210
## 4: 0.08803219 0.09212215 1.158314
## 5: 0.08954621 0.09372213 1.162563</code></pre>
<p><strong>mean for a continuous over windowed years</strong></p>
<div class="sourceCode" id="cb14"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb14-1"><a href="#cb14-1" aria-hidden="true" tabindex="-1"></a><span class="fu">calc</span>(<span class="at">ph.data =</span> birth, </span>
<span id="cb14-2"><a href="#cb14-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">what =</span> <span class="fu">c</span>(<span class="st">&quot;birth_weight_grams&quot;</span>), </span>
<span id="cb14-3"><a href="#cb14-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">metrics =</span> <span class="fu">c</span>(<span class="st">&quot;mean&quot;</span>, <span class="st">&quot;rse&quot;</span>), </span>
<span id="cb14-4"><a href="#cb14-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">time_var =</span> <span class="st">&quot;chi_year&quot;</span>, </span>
<span id="cb14-5"><a href="#cb14-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">win =</span> <span class="dv">3</span>)[]</span></code></pre></div>
<pre><code>##     chi_year           variable     mean level  mean_se mean_lower mean_upper
## 1: 2013-2015 birth_weight_grams 3339.469    NA 2.122024   3335.310   3343.628
## 2: 2014-2016 birth_weight_grams 3336.555    NA 2.087116   3332.465   3340.646
## 3: 2015-2017 birth_weight_grams 3333.507    NA 2.068735   3329.452   3337.562
## 4: 2016-2018 birth_weight_grams 3327.129    NA 2.073889   3323.065   3331.194
## 5: 2017-2019 birth_weight_grams 3320.961    NA 2.088449   3316.868   3325.055
##           rse
## 1: 0.06354375
## 2: 0.06255302
## 3: 0.06205880
## 4: 0.06233269
## 5: 0.06288689</code></pre>
<p><strong>mean for a continuous in 2019, by gender and
race/eth</strong></p>
<div class="sourceCode" id="cb16"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb16-1"><a href="#cb16-1" aria-hidden="true" tabindex="-1"></a><span class="fu">calc</span>(<span class="at">ph.data =</span> birth, </span>
<span id="cb16-2"><a href="#cb16-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">what =</span> <span class="fu">c</span>(<span class="st">&quot;birth_weight_grams&quot;</span>), </span>
<span id="cb16-3"><a href="#cb16-3" aria-hidden="true" tabindex="-1"></a>     chi_year <span class="sc">==</span> <span class="dv">2019</span>,</span>
<span id="cb16-4"><a href="#cb16-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">metrics =</span> <span class="fu">c</span>(<span class="st">&quot;mean&quot;</span>, <span class="st">&quot;rse&quot;</span>), </span>
<span id="cb16-5"><a href="#cb16-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">by =</span> <span class="fu">c</span>(<span class="st">&quot;chi_race_eth8&quot;</span>, <span class="st">&quot;chi_sex&quot;</span>))[]</span></code></pre></div>
<pre><code>##     chi_race_eth8 chi_sex           variable     mean level     mean_se
##  1:         White    Male birth_weight_grams 3460.298    NA    7.489711
##  2:         White  Female birth_weight_grams 3340.295    NA    7.280580
##  3:      Hispanic    Male birth_weight_grams 3301.784    NA   14.310447
##  4:         Black  Female birth_weight_grams 3196.872    NA   18.683442
##  5:      Multiple    Male birth_weight_grams 3369.178    NA   23.359494
##  6:       Oth/unk  Female birth_weight_grams 3223.599    NA   30.670381
##  7:         Asian    Male birth_weight_grams 3231.952    NA    9.784437
##  8:      Hispanic  Female birth_weight_grams 3270.074    NA   13.703835
##  9:         Asian  Female birth_weight_grams 3145.902    NA    9.419157
## 10:         Black    Male birth_weight_grams 3306.213    NA   19.794051
## 11:          NHPI    Male birth_weight_grams 3444.178    NA   43.324387
## 12:          NHPI  Female birth_weight_grams 3287.541    NA   49.322668
## 13:          AIAN  Female birth_weight_grams 3251.965    NA   79.070604
## 14:      Multiple  Female birth_weight_grams 3251.312    NA   24.365976
## 15:       Oth/unk    Male birth_weight_grams 3315.557    NA   33.357232
## 16:          AIAN    Male birth_weight_grams 3438.641    NA   84.306018
## 17:         White    &lt;NA&gt; birth_weight_grams 1873.500    NA 1321.500000
##     mean_lower mean_upper        rse
##  1:   3445.618   3474.977  0.2164470
##  2:   3326.026   3354.565  0.2179622
##  3:   3273.736   3329.832  0.4334156
##  4:   3160.253   3233.491  0.5844288
##  5:   3323.394   3414.962  0.6933292
##  6:   3163.487   3283.712  0.9514328
##  7:   3212.775   3251.129  0.3027408
##  8:   3243.215   3296.933  0.4190681
##  9:   3127.441   3164.363  0.2994104
## 10:   3267.418   3345.009  0.5986925
## 11:   3359.264   3529.092  1.2579021
## 12:   3190.871   3384.212  1.5002905
## 13:   3096.989   3406.940  2.4314716
## 14:   3203.556   3299.069  0.7494198
## 15:   3250.178   3380.936  1.0060823
## 16:   3273.404   3603.877  2.4517252
## 17: -14917.750  18664.750 70.5364291</code></pre>
<p><strong>Proportion of 2017-2019 births among each race/eth
group</strong></p>
<div class="sourceCode" id="cb18"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb18-1"><a href="#cb18-1" aria-hidden="true" tabindex="-1"></a><span class="fu">calc</span>(<span class="at">ph.data =</span> birth, </span>
<span id="cb18-2"><a href="#cb18-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">what =</span> <span class="fu">c</span>(<span class="st">&quot;chi_race_eth8&quot;</span>), </span>
<span id="cb18-3"><a href="#cb18-3" aria-hidden="true" tabindex="-1"></a>     chi_year <span class="sc">%in%</span> <span class="dv">2017</span><span class="sc">:</span><span class="dv">2019</span>,</span>
<span id="cb18-4"><a href="#cb18-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">metrics =</span> <span class="fu">c</span>(<span class="st">&quot;mean&quot;</span>, <span class="st">&quot;rse&quot;</span>, <span class="st">&quot;obs&quot;</span>, <span class="st">&quot;numerator&quot;</span>, <span class="st">&quot;denominator&quot;</span>))[]</span></code></pre></div>
<pre><code>##       level      variable denominator   obs       mean      mean_se  mean_lower
## 1:     AIAN chi_race_eth8       73701 73701 0.00530522 0.0002675857 0.004805929
## 2:    Asian chi_race_eth8       73701 73701 0.22911494 0.0015480599 0.226094981
## 3:    Black chi_race_eth8       73701 73701 0.09036512 0.0010560883 0.088316537
## 4: Hispanic chi_race_eth8       73701 73701 0.13007965 0.0012391123 0.127670314
## 5: Multiple chi_race_eth8       73701 73701 0.04203471 0.0007391714 0.040609678
## 6:     NHPI chi_race_eth8       73701 73701 0.01629557 0.0004663730 0.015406391
## 7:  Oth/unk chi_race_eth8       73701 73701 0.01867003 0.0004985932 0.017717604
## 8:    White chi_race_eth8       73701 73701 0.46813476 0.0018380296 0.464534068
##     mean_upper numerator       rse
## 1: 0.005856077       391 5.0438189
## 2: 0.232163131     16886 0.6756696
## 3: 0.092456411      6660 1.1686901
## 4: 0.132527538      9587 0.9525797
## 5: 0.043507475      3098 1.7584788
## 6: 0.017235175      1201 2.8619613
## 7: 0.019672633      1376 2.6705534
## 8: 0.471738775     34502 0.3926283</code></pre>
<p><strong>2017-2019 rate per 100k of births among each race/eth
group</strong></p>
<div class="sourceCode" id="cb20"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb20-1"><a href="#cb20-1" aria-hidden="true" tabindex="-1"></a><span class="fu">calc</span>(<span class="at">ph.data =</span> birth, </span>
<span id="cb20-2"><a href="#cb20-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">what =</span> <span class="fu">c</span>(<span class="st">&quot;chi_race_eth8&quot;</span>), </span>
<span id="cb20-3"><a href="#cb20-3" aria-hidden="true" tabindex="-1"></a>     chi_year <span class="sc">%in%</span> <span class="dv">2017</span><span class="sc">:</span><span class="dv">2019</span>,</span>
<span id="cb20-4"><a href="#cb20-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">metrics =</span> <span class="fu">c</span>(<span class="st">&quot;obs&quot;</span>, <span class="st">&quot;numerator&quot;</span>, <span class="st">&quot;denominator&quot;</span>, <span class="st">&quot;rate&quot;</span>), </span>
<span id="cb20-5"><a href="#cb20-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">per =</span> <span class="dv">100000</span>)[]</span></code></pre></div>
<pre><code>##       level      variable denominator   obs numerator      rate   rate_se
## 1:     AIAN chi_race_eth8       73701 73701       391   530.522  26.75857
## 2:    Asian chi_race_eth8       73701 73701     16886 22911.494 154.80599
## 3:    Black chi_race_eth8       73701 73701      6660  9036.512 105.60883
## 4: Hispanic chi_race_eth8       73701 73701      9587 13007.965 123.91123
## 5: Multiple chi_race_eth8       73701 73701      3098  4203.471  73.91714
## 6:     NHPI chi_race_eth8       73701 73701      1201  1629.557  46.63730
## 7:  Oth/unk chi_race_eth8       73701 73701      1376  1867.003  49.85932
## 8:    White chi_race_eth8       73701 73701     34502 46813.476 183.80296
##    rate_lower rate_upper rate_per
## 1:   480.5929   585.6077    1e+05
## 2: 22609.4981 23216.3131    1e+05
## 3:  8831.6537  9245.6411    1e+05
## 4: 12767.0314 13252.7538    1e+05
## 5:  4060.9678  4350.7475    1e+05
## 6:  1540.6391  1723.5175    1e+05
## 7:  1771.7604  1967.2633    1e+05
## 8: 46453.4068 47173.8775    1e+05</code></pre>
<p><strong>Number and proportion of missing gender by year</strong></p>
<div class="sourceCode" id="cb22"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb22-1"><a href="#cb22-1" aria-hidden="true" tabindex="-1"></a><span class="fu">calc</span>(<span class="at">ph.data =</span> birth, </span>
<span id="cb22-2"><a href="#cb22-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">what =</span> <span class="fu">c</span>(<span class="st">&quot;chi_sex&quot;</span>), </span>
<span id="cb22-3"><a href="#cb22-3" aria-hidden="true" tabindex="-1"></a>     chi_year <span class="sc">%in%</span> <span class="dv">2017</span><span class="sc">:</span><span class="dv">2019</span>,</span>
<span id="cb22-4"><a href="#cb22-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">metrics =</span> <span class="fu">c</span>(<span class="st">&quot;obs&quot;</span>, <span class="st">&quot;missing&quot;</span>, <span class="st">&quot;missing.prop&quot;</span>), </span>
<span id="cb22-5"><a href="#cb22-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">by =</span> <span class="st">&quot;chi_year&quot;</span>)[]</span></code></pre></div>
<pre><code>##    chi_year variable   obs missing missing.prop  level
## 1:     2017  chi_sex 25274       0   0.0000e+00 Female
## 2:     2017  chi_sex 25274       0   0.0000e+00   Male
## 3:     2018  chi_sex 24337       0   0.0000e+00   Male
## 4:     2018  chi_sex 24337       0   0.0000e+00 Female
## 5:     2019  chi_sex 24090       2   8.3022e-05   Male
## 6:     2019  chi_sex 24090       2   8.3022e-05 Female
## 7:     2019  chi_sex 24090       2   8.3022e-05   &lt;NA&gt;</code></pre>
<hr />
</div>
<div id="example-survey-analyses" class="section level2">
<h2>Example survey analyses</h2>
<p>Before using <code>calc()</code> with survey data, the user must
survey set the data while properly specifying the survey design. Here is
an example of how to set <a href="https://github.com/PHSKC-APDE/svy_acs">ACS PUMS</a> person level
data:</p>
<div class="sourceCode" id="cb24"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb24-1"><a href="#cb24-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(survey)</span>
<span id="cb24-2"><a href="#cb24-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-3"><a href="#cb24-3" aria-hidden="true" tabindex="-1"></a><span class="fu">load</span>(<span class="st">&quot;//phshare01/epe_share/WORK/surveys/ACS/PUMS_data/2019_1_year/prepped_R_files/2019_1_year_data.RData&quot;</span>)</span>
<span id="cb24-4"><a href="#cb24-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb24-5"><a href="#cb24-5" aria-hidden="true" tabindex="-1"></a>  pums <span class="ot">&lt;-</span>     </span>
<span id="cb24-6"><a href="#cb24-6" aria-hidden="true" tabindex="-1"></a>    survey<span class="sc">::</span><span class="fu">svrepdesign</span>(</span>
<span id="cb24-7"><a href="#cb24-7" aria-hidden="true" tabindex="-1"></a>      <span class="at">weight =</span> <span class="sc">~</span>pwgtp ,</span>
<span id="cb24-8"><a href="#cb24-8" aria-hidden="true" tabindex="-1"></a>      <span class="at">combined.weights =</span> <span class="cn">TRUE</span> ,</span>
<span id="cb24-9"><a href="#cb24-9" aria-hidden="true" tabindex="-1"></a>      <span class="at">repweights =</span> <span class="st">&#39;pwgtp[0-9]+&#39;</span> ,</span>
<span id="cb24-10"><a href="#cb24-10" aria-hidden="true" tabindex="-1"></a>      <span class="at">scale =</span> <span class="dv">4</span> <span class="sc">/</span> <span class="dv">80</span> ,</span>
<span id="cb24-11"><a href="#cb24-11" aria-hidden="true" tabindex="-1"></a>      <span class="at">rscales =</span> <span class="fu">rep</span>( <span class="dv">1</span> , <span class="dv">80</span> ) ,</span>
<span id="cb24-12"><a href="#cb24-12" aria-hidden="true" tabindex="-1"></a>      <span class="at">mse =</span> <span class="cn">TRUE</span> ,</span>
<span id="cb24-13"><a href="#cb24-13" aria-hidden="true" tabindex="-1"></a>      <span class="at">type =</span> <span class="st">&quot;JK1&quot;</span> ,</span>
<span id="cb24-14"><a href="#cb24-14" aria-hidden="true" tabindex="-1"></a>      <span class="at">data =</span> person.wa</span>
<span id="cb24-15"><a href="#cb24-15" aria-hidden="true" tabindex="-1"></a>    )</span>
<span id="cb24-16"><a href="#cb24-16" aria-hidden="true" tabindex="-1"></a>  </span>
<span id="cb24-17"><a href="#cb24-17" aria-hidden="true" tabindex="-1"></a>  <span class="co">#New for version 1.0.0</span></span>
<span id="cb24-18"><a href="#cb24-18" aria-hidden="true" tabindex="-1"></a>  pums <span class="ot">=</span>dtsurvey<span class="sc">::</span><span class="fu">dtrepsurvey</span>(pums)</span></code></pre></div>
<p>Once the data has been set as a survey, we can use the
<code>calc()</code> function the same way that we used it for vital
statistics (birth) data.</p>
<p><strong>Quick sanity check before proceeding.</strong></p>
<p>To confirm that the data has been survey set properly, it would be
wise to check if the survey weighted population is more or less what you
would expect.</p>
<p>When <code>calc</code> analyzes survey data, the
<code>numerator</code> is the number of observations in that category
and the <code>total</code> is the survey weighted value for those
observations. We know that the approximate 2019 populations of WA State,
King County, and Seattle were ~7.6 million, ~2.2 million, and 750,000,
respectively. How do the following 2019 ACS estimates (i.e.,
<code>total</code> values) compare?</p>
<div class="sourceCode" id="cb25"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb25-1"><a href="#cb25-1" aria-hidden="true" tabindex="-1"></a>pums[, constant <span class="sc">:</span><span class="er">=</span><span class="dv">1</span>]</span>
<span id="cb25-2"><a href="#cb25-2" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb25-3"><a href="#cb25-3" aria-hidden="true" tabindex="-1"></a><span class="co"># WA State</span></span>
<span id="cb25-4"><a href="#cb25-4" aria-hidden="true" tabindex="-1"></a><span class="fu">calc</span>(<span class="at">ph.data =</span> pums, </span>
<span id="cb25-5"><a href="#cb25-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">what =</span> <span class="fu">c</span>(<span class="st">&quot;constant&quot;</span>), </span>
<span id="cb25-6"><a href="#cb25-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">metrics =</span> <span class="fu">c</span>(<span class="st">&quot;numerator&quot;</span>, <span class="st">&quot;total&quot;</span>), </span>
<span id="cb25-7"><a href="#cb25-7" aria-hidden="true" tabindex="-1"></a>     <span class="at">proportion =</span> F)[]</span></code></pre></div>
<pre><code>##    variable   total numerator level total_se total_lower total_upper
## 1: constant 7614893     77879    NA        0     7614893     7614893</code></pre>
<div class="sourceCode" id="cb27"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb27-1"><a href="#cb27-1" aria-hidden="true" tabindex="-1"></a><span class="co"># King County</span></span>
<span id="cb27-2"><a href="#cb27-2" aria-hidden="true" tabindex="-1"></a><span class="fu">calc</span>(<span class="at">ph.data =</span> pums, </span>
<span id="cb27-3"><a href="#cb27-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">what =</span> <span class="fu">c</span>(<span class="st">&quot;constant&quot;</span>), </span>
<span id="cb27-4"><a href="#cb27-4" aria-hidden="true" tabindex="-1"></a>     chi_geo_kc <span class="sc">==</span><span class="dv">1</span>,</span>
<span id="cb27-5"><a href="#cb27-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">metrics =</span> <span class="fu">c</span>(<span class="st">&quot;numerator&quot;</span>, <span class="st">&quot;total&quot;</span>), </span>
<span id="cb27-6"><a href="#cb27-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">proportion =</span> F)[]</span></code></pre></div>
<pre><code>##    variable   total numerator level total_se total_lower total_upper
## 1: constant 2252619     20767    NA  1102.38     2250425     2254813</code></pre>
<div class="sourceCode" id="cb29"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb29-1"><a href="#cb29-1" aria-hidden="true" tabindex="-1"></a><span class="co"># Seattle</span></span>
<span id="cb29-2"><a href="#cb29-2" aria-hidden="true" tabindex="-1"></a><span class="fu">calc</span>(<span class="at">ph.data =</span> pums, </span>
<span id="cb29-3"><a href="#cb29-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">what =</span> <span class="fu">c</span>(<span class="st">&quot;constant&quot;</span>), </span>
<span id="cb29-4"><a href="#cb29-4" aria-hidden="true" tabindex="-1"></a>     chi_geo_seattle <span class="sc">==</span><span class="dv">1</span>,</span>
<span id="cb29-5"><a href="#cb29-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">metrics =</span> <span class="fu">c</span>(<span class="st">&quot;numerator&quot;</span>, <span class="st">&quot;total&quot;</span>), </span>
<span id="cb29-6"><a href="#cb29-6" aria-hidden="true" tabindex="-1"></a>     <span class="at">proportion =</span> F)[]</span></code></pre></div>
<pre><code>##    variable  total numerator level total_se total_lower total_upper
## 1: constant 752953      6526    NA 1077.184    750808.9    755097.1</code></pre>
<p>Now that we’ve established that our survey data is reasonable, we can
continue with our analyses.</p>
<p><strong>Mean (proportion) of those near poverty or disabled, by King
County (vs. remainder of WA)</strong></p>
<div class="sourceCode" id="cb31"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb31-1"><a href="#cb31-1" aria-hidden="true" tabindex="-1"></a><span class="fu">calc</span>(<span class="at">ph.data =</span> pums, </span>
<span id="cb31-2"><a href="#cb31-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">what =</span> <span class="fu">c</span>(<span class="st">&quot;disability&quot;</span>, <span class="st">&quot;GEpov200&quot;</span>), </span>
<span id="cb31-3"><a href="#cb31-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">metrics =</span> <span class="fu">c</span>(<span class="st">&quot;mean&quot;</span>, <span class="st">&quot;rse&quot;</span>, <span class="st">&quot;obs&quot;</span>, <span class="st">&quot;numerator&quot;</span>, <span class="st">&quot;denominator&quot;</span>), </span>
<span id="cb31-4"><a href="#cb31-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">proportion =</span> T, </span>
<span id="cb31-5"><a href="#cb31-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">by =</span> <span class="st">&quot;chi_geo_kc&quot;</span>)[]</span></code></pre></div>
<pre><code>##    chi_geo_kc   variable       mean numerator denominator   obs level
## 1:          0 disability 0.14337089      9038       57112 57112    NA
## 2:          1 disability 0.09965467      2310       20767 20767    NA
## 3:          0   GEpov200 0.73832042     41951       55069 57112    NA
## 4:          1   GEpov200 0.83492701     17250       20149 20767    NA
##        mean_se mean_lower mean_upper       rse
## 1: 0.001839847 0.13974757  0.1470721 1.2832777
## 2: 0.002899820 0.09402953  0.1055771 2.9098684
## 3: 0.004032853 0.73021413  0.7462678 0.5462199
## 4: 0.004949186 0.82483869  0.8445438 0.5927687</code></pre>
<p><strong>Proportion in each CHNA age group, by disability
status</strong></p>
<div class="sourceCode" id="cb33"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb33-1"><a href="#cb33-1" aria-hidden="true" tabindex="-1"></a><span class="fu">calc</span>(<span class="at">ph.data =</span> pums, </span>
<span id="cb33-2"><a href="#cb33-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">what =</span> <span class="fu">c</span>(<span class="st">&quot;agechna&quot;</span>), </span>
<span id="cb33-3"><a href="#cb33-3" aria-hidden="true" tabindex="-1"></a>     <span class="at">metrics =</span> <span class="fu">c</span>(<span class="st">&quot;mean&quot;</span>, <span class="st">&quot;rse&quot;</span>, <span class="st">&quot;obs&quot;</span>, <span class="st">&quot;numerator&quot;</span>, <span class="st">&quot;denominator&quot;</span>), </span>
<span id="cb33-4"><a href="#cb33-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">proportion =</span> F, </span>
<span id="cb33-5"><a href="#cb33-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">by =</span> <span class="st">&quot;disability&quot;</span>)[]</span></code></pre></div>
<pre><code>##     disability level variable denominator   obs       mean      mean_se
##  1:          0 18-24  agechna       66531 66531 0.09226661 0.0007193595
##  2:          0 25-44  agechna       66531 66531 0.30776057 0.0011119388
##  3:          0 45-64  agechna       66531 66531 0.24204020 0.0008892628
##  4:          0 65-74  agechna       66531 66531 0.08320689 0.0006653204
##  5:          0   75+  agechna       66531 66531 0.03492094 0.0005877849
##  6:          0   &lt;18  agechna       66531 66531 0.23980479 0.0006282212
##  7:          1 18-24  agechna       11348 11348 0.04838122 0.0030271433
##  8:          1 25-44  agechna       11348 11348 0.16410713 0.0048231944
##  9:          1 45-64  agechna       11348 11348 0.28470479 0.0042658589
## 10:          1 65-74  agechna       11348 11348 0.18640300 0.0041475334
## 11:          1   75+  agechna       11348 11348 0.24249002 0.0040969128
## 12:          1   &lt;18  agechna       11348 11348 0.07391385 0.0034421598
##     mean_lower mean_upper numerator       rse
##  1: 0.09083477 0.09369846      5771 0.7796531
##  2: 0.30554731 0.30997383     18128 0.3613000
##  3: 0.24027016 0.24381023     17535 0.3674029
##  4: 0.08188260 0.08453118      7137 0.7995977
##  5: 0.03375098 0.03609089      2996 1.6831876
##  6: 0.23855435 0.24105523     14964 0.2619719
##  7: 0.04235584 0.05440660       482 6.2568562
##  8: 0.15450680 0.17370746      1592 2.9390524
##  9: 0.27621381 0.29319577      3089 1.4983446
## 10: 0.17814754 0.19465846      2338 2.2250358
## 11: 0.23433532 0.25064472      3173 1.6895181
## 12: 0.06706240 0.08076530       674 4.6569890</code></pre>
<p><strong>Mean &amp; median age in King County, by disability
status</strong></p>
<div class="sourceCode" id="cb35"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb35-1"><a href="#cb35-1" aria-hidden="true" tabindex="-1"></a><span class="fu">calc</span>(<span class="at">ph.data =</span> pums, </span>
<span id="cb35-2"><a href="#cb35-2" aria-hidden="true" tabindex="-1"></a>     <span class="at">what =</span> <span class="fu">c</span>(<span class="st">&quot;agep&quot;</span>),</span>
<span id="cb35-3"><a href="#cb35-3" aria-hidden="true" tabindex="-1"></a>     chi_geo_kc <span class="sc">==</span> <span class="dv">1</span>,</span>
<span id="cb35-4"><a href="#cb35-4" aria-hidden="true" tabindex="-1"></a>     <span class="at">metrics =</span> <span class="fu">c</span>(<span class="st">&quot;mean&quot;</span>, <span class="st">&quot;median&quot;</span>, <span class="st">&quot;rse&quot;</span>, <span class="st">&quot;obs&quot;</span>, <span class="st">&quot;numerator&quot;</span>, <span class="st">&quot;denominator&quot;</span>), </span>
<span id="cb35-5"><a href="#cb35-5" aria-hidden="true" tabindex="-1"></a>     <span class="at">by =</span> <span class="st">&quot;disability&quot;</span>)[]</span></code></pre></div>
<pre><code>##    disability variable     mean median numerator denominator   obs level
## 1:          1     agep 57.92030     65    139502        2310  2310    NA
## 2:          0     agep 36.04553     37    694645       18457 18457    NA
##       mean_se mean_lower mean_upper       rse
## 1: 0.66318899   56.60026   59.24035 1.1450027
## 2: 0.08386155   35.87861   36.21246 0.2326545</code></pre>
<hr />
</div>
<div id="example-analyses-with-non-standard-data" class="section level2">
<h2>Example analyses with non-standard data</h2>
<p>In the examples above we used standard public health data (birth
vital statistics and the Census Bureau’s ACS survey). However, since
<code>calc()</code> is a generalized function, you can use it with
nearly any dataset, as long as it is a data.frame, a data.table, or a
survey object. To demonstrate this, we will use <code>calc()</code> with
synthetic data that we will generate below.</p>
<p><strong>Create the dataset</strong></p>
<div class="sourceCode" id="cb37"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb37-1"><a href="#cb37-1" aria-hidden="true" tabindex="-1"></a><span class="fu">library</span>(data.table)</span>
<span id="cb37-2"><a href="#cb37-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">98121</span>) </span>
<span id="cb37-3"><a href="#cb37-3" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-4"><a href="#cb37-4" aria-hidden="true" tabindex="-1"></a>mydt <span class="ot">&lt;-</span> <span class="fu">data.table</span>(</span>
<span id="cb37-5"><a href="#cb37-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">school =</span> <span class="fu">as.factor</span>(<span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">&quot;Alpha&quot;</span>, <span class="st">&quot;Beta&quot;</span>, <span class="st">&quot;Gamma&quot;</span>, <span class="st">&quot;Delta&quot;</span>), <span class="dv">2000</span>, <span class="at">replace =</span> T)),</span>
<span id="cb37-6"><a href="#cb37-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">grades =</span> <span class="fu">as.factor</span>(<span class="fu">sample</span>(<span class="fu">c</span>(<span class="st">&quot;A&quot;</span>, <span class="st">&quot;B&quot;</span>, <span class="st">&quot;C&quot;</span>, <span class="st">&quot;D&quot;</span>), <span class="dv">2000</span>, <span class="at">replace =</span> T)), </span>
<span id="cb37-7"><a href="#cb37-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">year =</span> <span class="fu">sample</span>(<span class="dv">2016</span><span class="sc">:</span><span class="dv">2021</span>, <span class="dv">2000</span>, <span class="at">replace =</span> T))</span>
<span id="cb37-8"><a href="#cb37-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-9"><a href="#cb37-9" aria-hidden="true" tabindex="-1"></a><span class="co">#New for version 1.0.0</span></span>
<span id="cb37-10"><a href="#cb37-10" aria-hidden="true" tabindex="-1"></a>mydt <span class="ot">=</span> dtsurvey<span class="sc">::</span><span class="fu">dtadmin</span>(mydt)</span>
<span id="cb37-11"><a href="#cb37-11" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb37-12"><a href="#cb37-12" aria-hidden="true" tabindex="-1"></a>mydt[]</span></code></pre></div>
<pre><code>##       school grades year  _id
##    1:  Alpha      A 2017    1
##    2:  Delta      B 2019    2
##    3:  Gamma      C 2017    3
##    4:   Beta      A 2016    4
##    5:  Delta      C 2018    5
##   ---                        
## 1996:  Alpha      C 2018 1996
## 1997:   Beta      B 2021 1997
## 1998:  Delta      C 2020 1998
## 1999:  Delta      D 2019 1999
## 2000:  Delta      D 2018 2000</code></pre>
<p>We see that we created a dataset of 2000 rows with grades in four
schools between with 2016 and 2021.</p>
<p><strong>Calculate the proportion of A’s and B’s in the Alpha and Beta
schools</strong></p>
<div class="sourceCode" id="cb39"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb39-1"><a href="#cb39-1" aria-hidden="true" tabindex="-1"></a>grades.distribution <span class="ot">&lt;-</span> <span class="fu">calc</span>(</span>
<span id="cb39-2"><a href="#cb39-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">ph.data =</span> mydt, </span>
<span id="cb39-3"><a href="#cb39-3" aria-hidden="true" tabindex="-1"></a>  school <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&quot;Alpha&quot;</span>, <span class="st">&quot;Beta&quot;</span>), </span>
<span id="cb39-4"><a href="#cb39-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">what =</span> <span class="st">&quot;grades&quot;</span>, </span>
<span id="cb39-5"><a href="#cb39-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">by =</span> <span class="st">&quot;school&quot;</span>, </span>
<span id="cb39-6"><a href="#cb39-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">time_var =</span> <span class="st">&quot;year&quot;</span>, </span>
<span id="cb39-7"><a href="#cb39-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">metrics =</span> <span class="fu">c</span>(<span class="st">&quot;numerator&quot;</span>, <span class="st">&quot;denominator&quot;</span>, <span class="st">&quot;mean&quot;</span>), <span class="at">proportion =</span> F)</span>
<span id="cb39-8"><a href="#cb39-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb39-9"><a href="#cb39-9" aria-hidden="true" tabindex="-1"></a>grades.distribution[level <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&quot;A&quot;</span>, <span class="st">&quot;B&quot;</span>)]</span></code></pre></div>
<pre><code>##    school level      year variable denominator      mean    mean_se mean_lower
## 1:  Alpha     A 2016-2021   grades         497 0.2857143 0.02028435  0.2477598
## 2:  Alpha     B 2016-2021   grades         497 0.2555332 0.01958418  0.2191639
## 3:   Beta     A 2016-2021   grades         491 0.2484725 0.01952152  0.2123012
## 4:   Beta     B 2016-2021   grades         491 0.2566191 0.01973114  0.2199795
##    mean_upper numerator
## 1:  0.3269560       142
## 2:  0.2956526       127
## 3:  0.2885490       122
## 4:  0.2970375       126</code></pre>
<p>These results show that the Alpha School has a higher proportion of
A’s (0.286 vs 0.248) and a similar proportion of B’s (0.256 vs
0.257).</p>
<p><strong>Wait! We forgot the survey weights!</strong></p>
<p>A colleague just reminded you that you forgot to add the survey
weights. Let’s add weights and survey set the data.</p>
<div class="sourceCode" id="cb41"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb41-1"><a href="#cb41-1" aria-hidden="true" tabindex="-1"></a><span class="co"># create weights</span></span>
<span id="cb41-2"><a href="#cb41-2" aria-hidden="true" tabindex="-1"></a><span class="fu">set.seed</span>(<span class="dv">98121</span>)</span>
<span id="cb41-3"><a href="#cb41-3" aria-hidden="true" tabindex="-1"></a>mydt[, mywghts <span class="sc">:</span><span class="er">=</span> <span class="fu">sample</span>(<span class="dv">50</span><span class="sc">:</span><span class="dv">1300</span>, <span class="dv">2000</span>, <span class="at">replace =</span> T)]</span>
<span id="cb41-4"><a href="#cb41-4" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb41-5"><a href="#cb41-5" aria-hidden="true" tabindex="-1"></a><span class="co"># survey set the data</span></span>
<span id="cb41-6"><a href="#cb41-6" aria-hidden="true" tabindex="-1"></a>mysvy <span class="ot">&lt;-</span>dtsurvey<span class="sc">::</span><span class="fu">dtsurvey</span>(<span class="fu">data.table</span>(mydt[, <span class="st">`</span><span class="at">_id</span><span class="st">`</span> <span class="sc">:</span><span class="er">=</span> <span class="cn">NULL</span>]), <span class="at">weight =</span> <span class="st">&#39;mywghts&#39;</span>)</span></code></pre></div>
<p><strong>Using the survey information, again calculate the proportion
of A’s and B’s in the Alpha and Beta schools</strong></p>
<div class="sourceCode" id="cb42"><pre class="sourceCode r"><code class="sourceCode r"><span id="cb42-1"><a href="#cb42-1" aria-hidden="true" tabindex="-1"></a>grades.distribution2 <span class="ot">&lt;-</span> <span class="fu">calc</span>(</span>
<span id="cb42-2"><a href="#cb42-2" aria-hidden="true" tabindex="-1"></a>  <span class="at">ph.data =</span> mysvy, </span>
<span id="cb42-3"><a href="#cb42-3" aria-hidden="true" tabindex="-1"></a>  school <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&quot;Alpha&quot;</span>, <span class="st">&quot;Beta&quot;</span>), </span>
<span id="cb42-4"><a href="#cb42-4" aria-hidden="true" tabindex="-1"></a>  <span class="at">what =</span> <span class="st">&quot;grades&quot;</span>, </span>
<span id="cb42-5"><a href="#cb42-5" aria-hidden="true" tabindex="-1"></a>  <span class="at">by =</span> <span class="st">&quot;school&quot;</span>, </span>
<span id="cb42-6"><a href="#cb42-6" aria-hidden="true" tabindex="-1"></a>  <span class="at">time_var =</span> <span class="st">&quot;year&quot;</span>, </span>
<span id="cb42-7"><a href="#cb42-7" aria-hidden="true" tabindex="-1"></a>  <span class="at">metrics =</span> <span class="fu">c</span>(<span class="st">&quot;numerator&quot;</span>, <span class="st">&quot;denominator&quot;</span>, <span class="st">&quot;mean&quot;</span>), <span class="at">proportion =</span> <span class="cn">FALSE</span>)</span>
<span id="cb42-8"><a href="#cb42-8" aria-hidden="true" tabindex="-1"></a></span>
<span id="cb42-9"><a href="#cb42-9" aria-hidden="true" tabindex="-1"></a>grades.distribution2[level <span class="sc">%in%</span> <span class="fu">c</span>(<span class="st">&quot;A&quot;</span>, <span class="st">&quot;B&quot;</span>)]</span></code></pre></div>
<pre><code>##    school level      year variable denominator      mean    mean_se mean_lower
## 1:  Alpha     A 2016-2021   grades         497 0.2819952 0.02280603  0.2371869
## 2:  Alpha     B 2016-2021   grades         497 0.2460211 0.02157805  0.2036254
## 3:   Beta     A 2016-2021   grades         491 0.2361366 0.02142621  0.1940380
## 4:   Beta     B 2016-2021   grades         491 0.2685865 0.02295556  0.2234831
##    mean_upper numerator
## 1:  0.3268036       142
## 2:  0.2884167       127
## 3:  0.2782351       122
## 4:  0.3136900       126</code></pre>
<p>You’ll note that using the survey design caused small changes in the
results. For examples, the proportion of A’s in the Alpha school changed
from 0.286 to 0.282.</p>
<hr />
</div>
<div id="knowing-is-half-the-battle-but-only-half" class="section level2">
<h2>Knowing is half the battle … but only half</h2>
<p>You’ve been introduced to <code>calc()</code>, but you’ll only become
competent at using it by using it. Try it out with your favorite
dataset. Use it to answer data requests. Play with it. Try to break it
and, if you’re successful, submit a <a href="https://github.com/PHSKC-APDE/rads/issues/new">GitHub issue</a>.
Enjoy!</p>
</div>



<!-- code folding -->


<!-- dynamically load mathjax for compatibility with self-contained -->
<script>
  (function () {
    var script = document.createElement("script");
    script.type = "text/javascript";
    script.src  = "https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML";
    document.getElementsByTagName("head")[0].appendChild(script);
  })();
</script>

</body>
</html>
