# Declare global variables for devtools::check()
utils::globalVariables(c(
  "comp_lower",
  "comp_se",
  "comp_upper",
  "contrast",
  "contrast_lower",
  "contrast_pvalue",
  "contrast_se",
  "contrast_upper",
  "lower_ci",
  "mean_est",
  "p_value",
  "ref_lower",
  "ref_se",
  "ref_upper",
  "rel_change_lower",
  "rel_change_mean",
  "rel_change_pval",
  "rel_change_upper",
  "upper_ci"
))
